version: '3'

services:
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Singapore2020!
    ports:
      - "5432:5432"